---
:verbose: false
:concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
:timeout: 30

:queues:
  - critical
  - default
  - low

#:schedule:
#  UpdateUrlJob:
#    cron: '* * * * *'
#    queue: scheduler
#    enabled: true